#ifndef COMPUTATIONAL_AGROECOLOGY_SIMULATOR_RESOURCE_H_
#define COMPUTATIONAL_AGROECOLOGY_SIMULATOR_RESOURCE_H_

namespace simulator {

enum ResourceType { MONEY = 0, TIME, MAN_POWER };

}

#endif  // COMPUTATIONAL_AGROECOLOGY_SIMULATOR_RESOURCE_H_