CC=g++
CFLAGS=-lGL -lGLU -lglut -lm
DEPS = Rendering_Control.cpp Rendering_Control.h Rendering_Grids.cpp Rendering_Grids.h Rendering_Plants.cpp Rendering_Plants.h Rendering_Weather.h main.cpp


opengl: $(DEPS)
	$(CC)  -o opengl $(DEPS)  $(CFLAGS) 
